### ISSUE TITLE
Make options page only accessible to users with correct permission

### ISSUE THREAD

**Issue by hchouhan** [webtions/i-recommend-this#17]
https://developer.wordpress.org/plugins/security/checking-user-capabilities/

**Comment by FPCSJames** [comment]
I tested this with an editor-level user and it's working as expected. When you create the options page and its menu item with add_options_page, the capability you set as the third parameter controls both the menu item display and page access. You have it set to manage_options, so by default only admins will see and be able to access it.

If you have a need to, you can also use [this filter](https://developer.wordpress.org/reference/hooks/option_page_capability_option_page/) after the fact.

**Comment by hchouhan** [comment]
This has already been fixed so closing the ticket.
