### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by zachwills** [webtions/i-recommend-this#6]
I have a few improvements I am probably going to be making to this for a client project (adding query caching and additional sanitization / escaping to queries / output) which I'd be happy to submit a PR for. If it's not being maintained I could fork it and apply the updates to the fork- so let me know what works best! :)

**Comment by hchouhan** [comment]
Hey Zach,

If you could submit a pull request that would be great as it could help other users too.
